<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: p2.php 273 2010-01-10 00:10:32Z schmunk $
 */
return array (
  '".$modelClass."' => '',
  'Admin' => '',
  'Administration' => '',
  'Application' => '',
  'Are you sure?' => '',
  'Assign Roles' => '',
  'Cell Configuration / Variation' => '',
  'Cell Properties' => '',
  'Cells' => '',
  'Common Tasks' => '',
  'Create' => '',
  'Create User' => '',
  'Create Widget Data' => '',
  'Created record' => '',
  'Data' => '',
  'Delete' => '',
  'Delete Data' => '',
  'E-Mail' => '',
  'Edit' => '',
  'Edit Cell Properties' => '',
  'Edit Data' => '',
  'Extended Options' => '',
  'Fields with <span class=\\"required\\">*</span> are required.' => '',
  'Files' => '',
  'First Name' => '',
  'Go to frontend' => '',
  'HTML' => '',
  'Home Page' => '',
  'Id' => '',
  'Info' => '',
  'Language {lang} is not available' => '',
  'Last Name' => '',
  'List' => '',
  'Log' => '',
  'Logout' => '',
  'Manage' => '',
  'Manage Roles' => '',
  'Manage Users' => '',
  'Manage Widgets' => '',
  'New' => '',
  'No record selected or created yet.' => '',
  'Pages' => '',
  'Password' => '',
  'P2' => 'π',
  'P2 Info' => '',
  'P2Html #{id} not found!' => '',
  'Please select ...' => '',
  'Please select a widget.' => '',
  'Repeat password please.' => '',
  'Return' => '',
  'Save' => '',
  'Save Widget Data' => '',
  'Select' => '',
  'Sending request ...' => '',
  'Show' => '',
  'Status' => '',
  'Unlink Widget' => '',
  'Update' => '',
  'Upload' => '',
  'Upload a file' => '',
  'Username' => '',
  'Users' => '',
  'View' => '',
  'View Roles' => '',
  'Welcome to p2' => '',
  '__USER_PROBLEMS__' => 'Still problems?! Please contact us by or by our <a href="{contactUrl}">contact page</a> or by <a href="mailto:{email}">e-mail</a>.',
  '__INSTALLATION_ROUTINE_WARNING__' => '',
  '__UNLINK_WIDGET__' => 'Do you really want to unlink the widget?',
  '__VALIDATION_ERROR_REGEXP_ALPHANUMERIC__' => '{attribute} must contain only letters, number or .-_, spaces are not allowed',
  'all' => '',
  'rank' => '',
  '{attribute} is not valid.' => '',
  '{attribute} is of the wrong length (should be {length} entries).' => '',
  '{attribute} is too long (maximum is {max} entries).' => '',
  '{attribute} is too short (minimum is {min} entries).' => '',
);
