<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: EJqueryFlash.php 273 2010-01-10 00:10:32Z schmunk $
 */
return array (
  'baseUrl must be set. This is done automatically by calling publishAssets()' => '',
  'callbacks must be an array' => '',
  'htmlOptions must be an array' => '',
  'pluginOptions must be an array' => '',
  '{k} is not a valid option' => '',
  '{k} must be of type {t}' => '',
  '{k} must be one of: {c}' => '',
  '{k} must be one of: {v}' => '',
);
